// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.15.8
// source: pb/wearable.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BeatsPerSecondRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
}

func (x *BeatsPerSecondRequest) Reset() {
	*x = BeatsPerSecondRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_wearable_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BeatsPerSecondRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeatsPerSecondRequest) ProtoMessage() {}

func (x *BeatsPerSecondRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_wearable_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeatsPerSecondRequest.ProtoReflect.Descriptor instead.
func (*BeatsPerSecondRequest) Descriptor() ([]byte, []int) {
	return file_pb_wearable_proto_rawDescGZIP(), []int{0}
}

func (x *BeatsPerSecondRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type BeatsPerSecondResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value  uint32 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	Second uint32 `protobuf:"varint,2,opt,name=second,proto3" json:"second,omitempty"`
}

func (x *BeatsPerSecondResponse) Reset() {
	*x = BeatsPerSecondResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_wearable_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BeatsPerSecondResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeatsPerSecondResponse) ProtoMessage() {}

func (x *BeatsPerSecondResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_wearable_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeatsPerSecondResponse.ProtoReflect.Descriptor instead.
func (*BeatsPerSecondResponse) Descriptor() ([]byte, []int) {
	return file_pb_wearable_proto_rawDescGZIP(), []int{1}
}

func (x *BeatsPerSecondResponse) GetValue() uint32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *BeatsPerSecondResponse) GetSecond() uint32 {
	if x != nil {
		return x.Second
	}
	return 0
}

var File_pb_wearable_proto protoreflect.FileDescriptor

var file_pb_wearable_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x62, 0x2f, 0x77, 0x65, 0x61, 0x72, 0x61, 0x62, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2b, 0x0a, 0x15, 0x42, 0x65,
	0x61, 0x74, 0x73, 0x50, 0x65, 0x72, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x22, 0x46, 0x0a, 0x16, 0x42, 0x65, 0x61, 0x74, 0x73,
	0x50, 0x65, 0x72, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x63, 0x6f, 0x6e,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x32,
	0x62, 0x0a, 0x0f, 0x57, 0x65, 0x61, 0x72, 0x61, 0x62, 0x6c, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x4f, 0x0a, 0x0e, 0x42, 0x65, 0x61, 0x74, 0x73, 0x50, 0x65, 0x72, 0x53, 0x65,
	0x63, 0x6f, 0x6e, 0x64, 0x12, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x65, 0x61,
	0x74, 0x73, 0x50, 0x65, 0x72, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x65, 0x61, 0x74, 0x73,
	0x50, 0x65, 0x72, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x30, 0x01, 0x42, 0x27, 0x5a, 0x25, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x6d, 0x75, 0x68, 0x61, 0x6d, 0x6d, 0x61, 0x64, 0x61, 0x72, 0x61, 0x73, 0x68, 0x31,
	0x39, 0x39, 0x37, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x35, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_wearable_proto_rawDescOnce sync.Once
	file_pb_wearable_proto_rawDescData = file_pb_wearable_proto_rawDesc
)

func file_pb_wearable_proto_rawDescGZIP() []byte {
	file_pb_wearable_proto_rawDescOnce.Do(func() {
		file_pb_wearable_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_wearable_proto_rawDescData)
	})
	return file_pb_wearable_proto_rawDescData
}

var file_pb_wearable_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pb_wearable_proto_goTypes = []interface{}{
	(*BeatsPerSecondRequest)(nil),  // 0: proto.BeatsPerSecondRequest
	(*BeatsPerSecondResponse)(nil), // 1: proto.BeatsPerSecondResponse
}
var file_pb_wearable_proto_depIdxs = []int32{
	0, // 0: proto.WearableService.BeatsPerSecond:input_type -> proto.BeatsPerSecondRequest
	1, // 1: proto.WearableService.BeatsPerSecond:output_type -> proto.BeatsPerSecondResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_wearable_proto_init() }
func file_pb_wearable_proto_init() {
	if File_pb_wearable_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_wearable_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BeatsPerSecondRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_wearable_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BeatsPerSecondResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_wearable_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_wearable_proto_goTypes,
		DependencyIndexes: file_pb_wearable_proto_depIdxs,
		MessageInfos:      file_pb_wearable_proto_msgTypes,
	}.Build()
	File_pb_wearable_proto = out.File
	file_pb_wearable_proto_rawDesc = nil
	file_pb_wearable_proto_goTypes = nil
	file_pb_wearable_proto_depIdxs = nil
}
